spring:
  profiles:
    active: common  # 현재 사용할 프로필 설정
    group:          # 특정 프로필 실행 시, 같이 실행할 그룹
      common: secret

---

spring:
  config:
    activate:
      on-profile: common  # 이 블록은 common 프로필이 활성화 시 로드됩니다.

  application:
    name: spring-boot-study

mybatis:
  mapper-locations: classpath:mappers/*.xml  # mapper 경로 지정
  type-aliases-package: com.koreait.spring_boot_study.entity  # entity 경로 지정

